---
title: "Bag of Words"
output: html_notebook
---


# Bag of Words on Reviews provided on IMDB.
Source: https://www.kaggle.com/c/word2vec-nlp-tutorial/details/part-1-for-beginners-bag-of-words

```{r, message=FALSE}
library(qdap)
library(tm)
```

```{r}

data <- read.table("../BagOfWordsdata/unlabeledTrainData.tsv", sep = "\t", header = TRUE, stringsAsFactors = FALSE)

data <- data$review
class(data)

source <- VectorSource(data)
corpus <- VCorpus(source)

clean_corpus <- function(x){
  x <- tolower(x)
  x <- removeWords(x, stopwords("en"))
  x <- stripWhitespace(x)
  x <- removePunctuation(x)
  return (x)
}

tm_clean <- function(corpus){
    corpus <- tm_map(corpus, removePunctuation)
    corpus <- tm_map(corpus, stripWhitespace)
    corpus <- tm_map(corpus, removeWords, stopwords("en"))
    return(corpus)
  }

corpus <- tm_clean(corpus)

# transform the Corpus into a TDM. So as to gather different term occurences.
corpus_tdm <- TermDocumentMatrix(corpus)

# convert the TDM into a Matrix.
corpus_tdm_m <- as.matrix(corpus_tdm)

#corpus_tdm_m <- rowSums(corpus_tdm_m)
```

